def get_infectious_diseases():
    return [
        {
            "title": "Tuberculosis (TB)",
            "category": "Infectious Disease",
            "definition": "A potentially serious infectious bacterial disease that mainly affects the lungs.",
            "causes": "Caused by the bacterium *Mycobacterium tuberculosis*. It spreads from person to person through microscopic droplets released into the air when an infected person coughs, speaks, or sneezes.",
            "risk_factors": "Weakened immune system (HIV/AIDS, diabetes), living in or traveling to certain areas (Africa, Asia, Eastern Europe), poverty, substance abuse, and working in healthcare.",
            "symptoms": "**Active TB:**<br><ul><li>Coughing that lasts three or more weeks</li><li>Coughing up blood or mucus</li><li>Chest pain</li><li>Unintentional weight loss</li><li>Fatigue</li><li>Fever and night sweats</li></ul>",
            "diagnosis": "A simple skin test (Mantoux test) or blood test can determine if you have the TB bacteria. An X-ray or CT scan of the chest and testing of sputum (phlegm) confirms active TB.",
            "treatment": "Unlike other bacterial infections which are treated with an antibiotic for a week or two, active TB requires taking multiple antibiotics for 6 to 9 months.",
            "medicines": "<ul><li>**Isoniazid**</li><li>**Rifampin (Rifadin, Rimactane)**</li><li>**Ethambutol (Myambutol)**</li><li>**Pyrazinamide**</li></ul>",
            "diet": "**To Eat:** High-calorie, protein-rich foods (lean meat, poultry, fish, eggs, dairy). Foods rich in Vitamin A, C, and E. Whole grains and lots of fresh fruits and vegetables.<br>**To Avoid:** Alcohol (can cause liver toxicity when combined with TB drugs), excess caffeine, refined sugars.",
            "home_remedies": "<ul><li>Get plenty of rest and fresh air.</li><li>Keep the windows open whenever possible (TB bacteria thrive in enclosed spaces).</li><li>Cover your mouth when coughing.</li></ul>",
            "prevention": "In many countries, children are vaccinated with the BCG vaccine. If you have latent TB, take your medication to prevent it from becoming active. Ensure good ventilation.",
            "recovery_time": "It takes at least 6 to 9 months of continuous medication to cure TB. Do not stop taking the medicine early, or the bacteria may become drug-resistant.",
            "when_to_see_doctor": "See a doctor immediately if you have a persistent cough outlasting a cold, especially if accompanied by fever, night sweats, or unexplained weight loss."
        },
        {
            "title": "Cholera",
            "category": "Infectious Disease",
            "definition": "An acute diarrheal illness caused by infection of the intestine with bacteria. In severe cases, it can cause rapidly fatal dehydration.",
            "causes": "Caused by the bacterium *Vibrio cholerae*. People usually get cholera by drinking water or eating food contaminated with the bacteria (fecal-oral route).",
            "risk_factors": "Living in or traveling to areas with poor sanitation, poor hygiene, and lack of safe drinking water. Raw or undercooked shellfish from certain waters can also be a source.",
            "symptoms": "**Classic Symptoms:**<br><ul><li>Profuse, watery diarrhea (often described as 'rice-water stools')</li><li>Vomiting</li><li>Leg cramps</li><li>Rapid loss of body fluids leading to severe dehydration (dry mouth, extreme thirst, sunken eyes)</li></ul>",
            "diagnosis": "Confirmed through a stool sample or a rectal swab to isolate the bacteria. Rapid dipstick tests are often used in outbreak settings.",
            "treatment": "Cholera is easily treatable, but time is of the essence. The primary treatment is immediate rehydration—replacing the fluid and salts lost through diarrhea.",
            "medicines": "<ul><li>**Oral Rehydration Solution (ORS):** A prepackaged mixture of sugar and salts to be mixed with water.</li><li>**Intravenous (IV) Fluids:** Required for severe dehydration.</li><li>**Antibiotics:** (like Doxycycline or Azithromycin) to reduce the duration of diarrhea.</li><li>**Zinc supplements:** Often given to children.</li></ul>",
            "diet": "**To Eat:** Initially, only ORS and clear fluids. As tolerance improves, easily digestible foods like plain rice, bananas, and crackers.<br>**To Avoid:** High-fiber foods, dairy products, spicy, and greasy foods.",
            "home_remedies": "<ul><li>Continuous sipping of ORS or homemade salt-sugar-water solution.</li><li>Strict bed rest.</li></ul>",
            "prevention": "Drink only bottled or boiled water. Wash hands with soap frequently. Eat food that is completely cooked and hot. Avoid raw seafood and unpeeled fruits in high-risk areas. Oral cholera vaccines are available.",
            "recovery_time": "With proper fluid replacement, recovery can begin in just a few days. Without treatment, death can occur within hours.",
            "when_to_see_doctor": "Seek emergency medical care immediately if you develop severe, watery diarrhea, especially after traveling to an area where cholera is common."
        },
        {
            "title": "COVID-19 (Coronavirus Disease)",
            "category": "Infectious Disease",
            "definition": "An infectious disease caused by the SARS-CoV-2 virus, primarily affecting the respiratory system but capable of causing systemic inflammation.",
            "causes": "Spreads mainly from person to person through respiratory droplets produced when an infected person coughs, sneezes, or talks. It can also spread via contaminated surfaces.",
            "risk_factors": "Older age, and underlying medical conditions such as cardiovascular disease, diabetes, chronic respiratory disease, and cancer increase the risk of severe illness.",
            "symptoms": "**Common:**<br><ul><li>Fever or chills</li><li>Cough</li><li>Shortness of breath</li><li>Fatigue</li><li>New loss of taste or smell</li></ul>**Severe:**<br><ul><li>Trouble breathing</li><li>Persistent chest pain</li><li>New confusion</li><li>Pale, gray, or blue skin/lips/nail beds</li></ul>",
            "diagnosis": "Diagnosed via a viral test (PCR or antigen test) using a nasal or throat swab. Chest X-rays or CT scans may be used to assess lung damage.",
            "treatment": "Treatment ranges from supportive care in mild cases to intensive care with respiratory support (oxygen or ventilators) in severe cases.",
            "medicines": "<ul><li>**Antiviral drugs:** Nirmatrelvir/Ritonavir (Paxlovid), Remdesivir.</li><li>**Anti-inflammatory drugs:** Corticosteroids (like Dexamethasone) for severe cases.</li><li>**Over-the-counter:** Acetaminophen or Ibuprofen for fever and pain.</li></ul>",
            "diet": "**To Eat:** Nutrient-dense foods. High vitamin C foods (citrus), zinc, and protein to support immune function. Drink plenty of water and warm teas.<br>**To Avoid:** Highly processed foods, excessive sugar, and alcohol which can weaken the immune response.",
            "home_remedies": "<ul><li>Rest heavily and stay hydrated.</li><li>Use a cool-mist humidifier.</li><li>Isolate from others to prevent spreading.</li><li>Monitor oxygen saturation with a pulse oximeter.</li></ul>",
            "prevention": "Stay up to date with COVID-19 vaccines. Wear high-quality masks (N95/KN95) in crowded indoor spaces. Practice social distancing. Maintain good ventilation indoors. Wash hands frequently.",
            "recovery_time": "Mild cases generally resolve in 1 to 2 weeks. Severe cases can take months, and some individuals experience 'Long COVID' with lingering symptoms for over a year.",
            "when_to_see_doctor": "Seek emergency medical care immediately if you have trouble breathing, persistent pain or pressure in the chest, new confusion, or inability to wake or stay awake."
        },
        {
            "title": "Influenza (The Flu)",
            "category": "Infectious Disease",
            "definition": "A highly contagious viral infection that attacks your respiratory system—your nose, throat, and lungs. It is not the same as stomach 'flu' viruses.",
            "causes": "Caused by influenza viruses (Types A and B are most responsible for seasonal flu epidemics). Spreads through respiratory droplets when sick people cough, sneeze, or talk.",
            "risk_factors": "Young children under 5 (especially under 2), adults over 65, pregnant women, and people with weakened immune systems or chronic illnesses (asthma, heart disease).",
            "symptoms": "**Classic Symptoms:**<br><ul><li>Sudden onset of fever (usually high) and chills</li><li>Muscle or body aches</li><li>Cough (usually dry)</li><li>Fatigue and severe weakness</li><li>Headache</li><li>Sore throat and runny nose</li></ul>",
            "diagnosis": "Most often diagnosed based on symptoms, especially during flu season. Rapid Influenza Diagnostic Tests (RIDTs) can identify the virus via a nasal or throat swab in 10-15 minutes.",
            "treatment": "For most people, the flu simply requires heavy rest and fluids to let the body fight the infection. Antiviral drugs can be prescribed for high-risk individuals if caught early.",
            "medicines": "<ul><li>**Antivirals:** Oseltamivir (Tamiflu), Zanamivir (Relenza), Peramivir (Rapivab), or Baloxavir marboxil (Xofluza).</li><li>**OTC Meds:** Acetaminophen, Ibuprofen, decongestants, and cough syrups for symptom relief.</li></ul>",
            "diet": "**To Eat:** Chicken soup, broth, herbal teas with honey (for cough), easily digestible foods, fruits rich in Vitamin C.<br>**To Avoid:** Dairy (can thicken mucus), alcohol, caffeine.",
            "home_remedies": "<ul><li>Stay home and rest extensively.</li><li>Drink plenty of warm liquids.</li><li>Use saline drops to clear a blocked nose.</li><li>Gargle saltwater for a sore throat.</li></ul>",
            "prevention": "The most effective prevention is the annual flu vaccine. Wash hands frequently. Avoid touching your face. Stay away from people who are sick. Cover your coughs and sneezes.",
            "recovery_time": "The fever and body aches usually last 3 to 5 days, but the cough and general fatigue can persist for 2 weeks or more.",
            "when_to_see_doctor": "See a doctor if you are in a high-risk group and suspect the flu. Seek emergency care for difficulty breathing, chest pain, dizziness, severe muscle pain, or a fever that comes back after going away."
        },
        {
            "title": "Chickenpox",
            "category": "Infectious Disease",
            "definition": "A highly contagious viral infection causing an itchy, blister-like rash on the skin. It was once a common childhood disease.",
            "causes": "Caused by the varicella-zoster virus (VZV). It spreads easily from people with chickenpox to others who have never had the disease or never been vaccinated, through the air or by touching the fluid from blisters.",
            "risk_factors": "Children under 12, pregnant women, people with weakened immune systems, and anyone who hasn't been vaccinated or hasn't had the disease naturally.",
            "symptoms": "**Early:**<br><ul><li>Fever</li><li>Loss of appetite</li><li>Headache</li><li>Tiredness and general feeling of being unwell (malaise)</li></ul>**The Rash:**<br><ul><li>Raised pink or red bumps (papules)</li><li>Small fluid-filled blisters (vesicles) that break and leak</li><li>Crusts and scabs over the broken blisters</li></ul>",
            "diagnosis": "Doctors generally diagnose chickenpox entirely based on the distinctive appearance of the rash.",
            "treatment": "In otherwise healthy children, chickenpox typically requires no medical treatment. The focus is on relieving symptoms and preventing skin infections.",
            "medicines": "<ul><li>**Fever/Pain Relief:** Acetaminophen. (NEVER give aspirin to children due to the risk of Reye's syndrome).</li><li>**Anti-itch:** Calamine lotion or oral antihistamines (like Benadryl).</li><li>**Antivirals:** (Like Acyclovir) may be prescribed for adults or high-risk patients.</li></ul>",
            "diet": "**To Eat:** Soft, bland, cool foods if blisters develop in the mouth (Popsicles, yogurt, oatmeal, scrambled eggs). Drink plenty of cold fluids.<br>**To Avoid:** Salty, spicy, acidic, or hard/crunchy foods that might irritate mouth sores.",
            "home_remedies": "<ul><li>Take cool or lukewarm oatmeal baths (colloidal oatmeal) or baking soda baths.</li><li>Apply calamine lotion to the blisters.</li><li>Keep fingernails cut very short to prevent scratching and secondary bacterial infections.</li></ul>",
            "prevention": "The most effective way to prevent chickenpox is to get the chickenpox (varicella) vaccine. Routine vaccination is recommended for children.",
            "recovery_time": "Normally, new spots stop appearing by the 7th day, and the person feels completely better within 10 to 14 days when all scabs have crusted over.",
            "when_to_see_doctor": "See a doctor if the rash spreads to one or both eyes, if the rash gets very red, warm, or tender (indicating a bacterial skin infection), or if accompanied by dizziness, shortness of breath, or a stiff neck."
        },
        {
            "title": "Measles",
            "category": "Infectious Disease",
            "definition": "A highly contagious, serious airborne viral disease that can lead to severe complications. It causes a total-body skin rash and flu-like symptoms.",
            "causes": "Caused by the measles virus (a paramyxovirus). It lives in the mucus of the nose and throat of an infected child or adult and spreads through coughing and sneezing.",
            "risk_factors": "Being unvaccinated, traveling to areas where measles is more common, and having a vitamin A deficiency.",
            "symptoms": "**Early (Prodromal):**<br><ul><li>High fever</li><li>Cough</li><li>Runny nose (coryza)</li><li>Inflamed, red, watery eyes (conjunctivitis)</li><li>Koplik spots (tiny white spots inside the mouth)</li></ul>**Later:**<br><ul><li>A flat red blotchy rash that begins on the face and spreads downward to the trunk and extremities.</li></ul>",
            "diagnosis": "Often diagnosed based on the characteristic rash and Koplik's spots. Can be confirmed with a blood test to check for the measles virus or an antibodies test, or via a throat or nasal swab.",
            "treatment": "There is no specific prescription medical treatment for an established measles infection. Treatment focuses on relieving symptoms and addressing complications like pneumonia or ear infections quickly.",
            "medicines": "<ul><li>**Fever Reducers:** Acetaminophen or Ibuprofen (no aspirin for children).</li><li>**Vitamin A supplements:** Given by doctors, as measles severity is linked to low Vitamin A.</li><li>**Antibiotics:** Only if a secondary bacterial infection (like an ear infection or pneumonia) occurs.</li></ul>",
            "diet": "**To Eat:** A highly nutritious diet with lots of fluids. Foods rich in Vitamin A (carrots, sweet potatoes, spinach) to support eye and immune health.<br>**To Avoid:** Processed foods and excessive sugars.",
            "home_remedies": "<ul><li>Rest extensively in a dimly lit room (measles makes eyes highly sensitive to light).</li><li>Use a humidifier to ease respiratory symptoms.</li><li>Sip fluids throughout the day.</li></ul>",
            "prevention": "The MMR (measles, mumps, rubella) vaccine is extremely effective and safe at preventing the disease.",
            "recovery_time": "The rash usually lasts 5 to 6 days. The cough may linger for 1 to 2 weeks. Full recovery usually takes about 2 to 3 weeks.",
            "when_to_see_doctor": "See a doctor IMMEDIATELY if you suspect measles. Measles complications (like pneumonia, encephalitis) can be fatal. Call ahead before going to the clinic so they can prepare to isolate the patient."
        },
        {
            "title": "Hepatitis B",
            "category": "Infectious Disease",
            "definition": "A serious liver infection caused by the hepatitis B virus (HBV). For some people, hepatitis B infection becomes chronic, meaning it lasts more than six months and increases the risk of developing liver failure, liver cancer, or cirrhosis.",
            "causes": "Spreads when blood, semen, or other body fluids from a person infected with the virus enters the body of someone who is not infected (sexual contact, sharing needles, or from mother to baby at birth).",
            "risk_factors": "Unprotected sex with multiple partners, men who have sex with men, sharing needles during IV drug use, living with someone who has chronic HBV, and working in a healthcare profession exposed to human blood.",
            "symptoms": "**Acute (if any appear):**<br><ul><li>Abdominal pain (especially in the upper right quadrant)</li><li>Dark urine</li><li>Fever</li><li>Joint pain</li><li>Loss of appetite, nausea, and vomiting</li><li>Weakness and fatigue</li><li>Yellowing of your skin and the whites of your eyes (jaundice)</li></ul>",
            "diagnosis": "Diagnosed via comprehensive blood tests that look for signs of the virus (antigens) and signs of the immune system fighting the virus (antibodies). Ultrasound or liver biopsy may be used to assess liver damage.",
            "treatment": "Acute hepatitis B mostly requires no treatment; your body clears it on its own. Chronic hepatitis B requires treatment to reduce the risk of liver disease and prevent passing the infection to others.",
            "medicines": "<ul><li>**For Chronic HBV:** Antiviral medications (Entecavir, Tenofovir, Lamivudine, Adefovir, Telbivudine).</li><li>**Interferon injections:** A man-made version of a substance produced by the body to fight infection.</li></ul>",
            "diet": "**To Eat:** A liver-friendly diet: lots of fruits, vegetables, whole grains, and lean proteins. Drink plenty of water.<br>**To Avoid:** ALCOHOL completely (it rapidly accelerates liver damage). Avoid high-fat, fried, and heavily processed foods.",
            "home_remedies": "<ul><li>Avoid medications that the liver processes unnecessarily (always check with a doctor before taking Tylenol/Acetaminophen).</li><li>Get plenty of rest.</li><li>Do not engage in unprotected sex.</li></ul>",
            "prevention": "The Hepatitis B vaccine is highly effective and normally administered to infants shortly after birth. Practice safe sex, do not share needles or personal care items like razors or toothbrushes.",
            "recovery_time": "Acute hepatitis B usually clears in a few weeks to months. Chronic hepatitis B is a lifelong condition requiring ongoing management.",
            "when_to_see_doctor": "See a doctor immediately if you know you've been exposed to hepatitis B (a preventative injection can be given within 24 hours). See a doctor if you develop jaundice or severe unexplained abdominal pain."
        }
    ]
