def get_digestive_skin_diseases():
    return [
        {
            "title": "Gastritis",
            "category": "Digestive System Disease",
            "definition": "An inflammation, irritation, or erosion of the lining of the stomach. It can occur suddenly (acute) or gradually (chronic).",
            "causes": "Most commonly caused by infection with *Helicobacter pylori* bacteria. Other causes include regular use of pain relievers (NSAIDs like Ibuprofen), heavy alcohol use, stress, and autoimmune disorders.",
            "risk_factors": "Frequent use of over-the-counter pain relievers, older age, excessive alcohol consumption, extreme physiological stress (from severe illness or surgery), and autoimmune conditions.",
            "symptoms": "**Common:**<br><ul><li>Gnawing or burning ache or pain (indigestion) in your upper abdomen that may become either worse or better with eating</li><li>Nausea and vomiting</li><li>A feeling of fullness in your upper abdomen after eating</li></ul>**Severe:**<br><ul><li>Vomiting blood or material that looks like coffee grounds</li><li>Black, tarry stools</li></ul>",
            "diagnosis": "Diagnosed via a physical exam and medical history. Tests may include a blood, stool, or breath test for *H. pylori*, an upper endoscopy (to visually inspect the stomach lining), or an X-ray of the upper digestive system.",
            "treatment": "Treatment depends on the specific cause. If caused by NSAIDs or alcohol, stopping those substances may be enough. If caused by an infection, you will need a course of antibiotics and acid blockers.",
            "medicines": "<ul><li>**Antibiotics:** To kill *H. pylori*.</li><li>**Proton Pump Inhibitors (PPIs):** (Omeprazole, Lansoprazole) to aggressively reduce stomach acid.</li><li>**Acid blockers (H-2 blockers):** (Famotidine) to reduce acid production.</li><li>**Antacids:** To neutralize existing stomach acid for rapid pain relief.</li></ul>",
            "diet": "**To Eat:** Small, frequent meals. Easily digestible foods like lean proteins, bananas, applesauce, rice, and toast (BRAT diet).<br>**To Avoid:** Spicy, acidic, fried, or fatty foods. Extremely hot beverages, alcohol, and caffeine, all of which irritate the stomach lining.",
            "home_remedies": "<ul><li>Avoid lying down immediately after eating.</li><li>Manage stress through relaxation techniques.</li><li>Stop smoking, as it damages the stomach lining.</li></ul>",
            "prevention": "Avoid heavily using NSAID pain relievers. Drink alcohol in moderation or not at all. Practice good hygiene (washing hands) to prevent *H. pylori* infections.",
            "recovery_time": "Acute gastritis often clears up within a few days once the irritant is removed. Chronic gastritis requires longer-term management and treatment of underlying infections.",
            "when_to_see_doctor": "See a doctor if your stomach discomfort lasts more than a week. Seek emergency care if you vomit blood or have black, tarry stools (signs of internal bleeding)."
        },
        {
            "title": "Peptic Ulcer Disease",
            "category": "Digestive System Disease",
            "definition": "A condition in which painful sores or ulcers develop in the lining of the stomach, lower esophagus, or first part of the small intestine (duodenum).",
            "causes": "The two most common causes are an infection with *Helicobacter pylori* bacteria and long-term use of nonsteroidal anti-inflammatory drugs (NSAIDs) such as ibuprofen and naproxen sodium. Spicy foods and stress do *not* cause ulcers, but they can make them worse.",
            "risk_factors": "Frequent use of NSAID pain relievers, smoking (increases risk if infected with *H. pylori*), heavy alcohol consumption, and having untreated stress that worsens symptoms.",
            "symptoms": "**Common:**<br><ul><li>Burning stomach pain (the most common symptom, often worsened on an empty stomach)</li><li>Feeling of fullness, bloating, or belching</li><li>Intolerance to fatty foods</li><li>Heartburn and nausea</li></ul>",
            "diagnosis": "Similar to gastritis: Endoscopy is the most accurate diagnostic tool. Laboratory tests for *H. pylori* (blood, breath, or stool) are routinely performed. Upper gastrointestinal X-rays may also be used.",
            "treatment": "Treatment involves killing the *H. pylori* bacterium if it's present, eliminating or reducing use of NSAIDs if possible, and helping your ulcer to heal with medication.",
            "medicines": "<ul><li>**Antibiotics:** To eradicate *H. pylori*.</li><li>**Proton Pump Inhibitors (PPIs):** To aggressively suppress acid production to allow the ulcer to heal.</li><li>**Bismuth subsalicylate (Pepto-Bismol):** Sometimes used in conjunction with antibiotics to kill the bacteria.</li></ul>",
            "diet": "**To Eat:** High-fiber foods (apples, pears, oatmeal) to lower acid concentration in the stomach. Foods with probiotics.<br>**To Avoid:** Spicy foods, citrus fruits, tomatoes, caffeine, and alcohol, which can cause intense pain when they hit the raw ulcer.",
            "home_remedies": "<ul><li>Do not smoke; it interferes with the protective lining of the stomach.</li><li>Control stress, which can worsen ulcer pain.</li><li>Get plenty of sleep to aid the body's healing processes.</li></ul>",
            "prevention": "Protect yourself from infections by washing hands frequently. Be cautious with pain relievers; use the lowest effective dose of NSAIDs and take them with food.",
            "recovery_time": "Uncomplicated peptic ulcers take about two to three months to heal completely with proper medical treatment.",
            "when_to_see_doctor": "Seek emergency medical attention if you experience sudden, severe abdominal pain, faintness, or if you vomit blood or have black, bloody stools (signs of a perforated ulcer or bleeding)."
        },
        {
            "title": "Appendicitis",
            "category": "Digestive System Disease",
            "definition": "An inflammation of the appendix, a finger-shaped pouch that projects from your colon on the lower right side of your abdomen. It is a medical emergency that requires prompt surgery.",
            "causes": "Usually caused by a blockage in the lining of the appendix that results in infection. The bacteria multiply rapidly, causing the appendix to become inflamed, swollen, and filled with pus.",
            "risk_factors": "Can happen at any age, but most often occurs in people between the ages of 10 and 30. More common in males.",
            "symptoms": "**Classic Progression:**<br><ol><li>Sudden pain that begins on the right side of the lower abdomen, OR pain that begins around your navel and shifts to your lower right abdomen.</li><li>Pain worsens if you cough, walk, or make jarring movements.</li><li>Nausea and vomiting develop.</li><li>Loss of appetite.</li><li>Low-grade fever that may worsen as the illness progresses.</li></ol>",
            "diagnosis": "Doctors diagnose appendicitis through a physical exam (checking for localized tenderness), blood tests (checking for high white blood cell count), urine tests (to rule out kidney stones), and imaging tests like a CT scan or ultrasound.",
            "treatment": "Appendicitis is almost always treated as a surgical emergency. The standard treatment is the surgical removal of the appendix, known as an appendectomy (often done laparoscopically).",
            "medicines": "<ul><li>**Antibiotics:** Administered intravenously before and sometimes after surgery to prevent or treat infection.</li><li>**Pain Relievers:** Given strictly under medical supervision in the hospital setting.</li></ul>",
            "diet": "**To Eat:** You must consume NOTHING by mouth (NPO) if appendicitis is suspected, as you may need emergency surgery and must have an empty stomach for anesthesia.<br>**Post-Surgery:** Clear liquids initially, progressing to a regular diet as tolerated.",
            "home_remedies": "<ul><li>**DO NOT USE HOME REMEDIES.** Never take laxatives, enemas, or pain relievers if you suspect appendicitis, as they can cause the appendix to burst or mask critical symptoms.</li></ul>",
            "prevention": "There is no way to completely prevent appendicitis. However, it may be less common in people who eat foods high in fiber, such as fresh fruits and vegetables.",
            "recovery_time": "If the appendix is removed before it bursts, recovery time is quick (1 to 3 weeks). If it bursts, recovery takes much longer and requires extensive antibiotic treatment for the abdominal infection.",
            "when_to_see_doctor": "Go to the nearest emergency room IMMEDIATELY if you or your child exhibits the classic shifting abdominal pain accompanied by nausea and fever. A ruptured appendix is a life-threatening crisis."
        },
        {
            "title": "Jaundice",
            "category": "Digestive System Disease",
            "definition": "Not a disease itself, but a profound symptom of an underlying medical condition. It causes a yellowish discoloration of the skin, mucous membranes, and the whites of the eyes due to high levels of bilirubin.",
            "causes": "Jaundice occurs when there's too much bilirubin (a yellow pigment formed by the breakdown of dead red blood cells) in the blood. This usually indicates a problem with the liver, gallbladder, or pancreas (e.g., Hepatitis, gallstones, cirrhosis).",
            "risk_factors": "Alcohol abuse, exposure to hepatitis viruses, taking medications processed heavily by the liver, having gallstones, or having a blood disorder that rapidly destroys red blood cells.",
            "symptoms": "**Common:**<br><ul><li>Yellow tinge to the skin and the whites of the eyes (sclera)</li><li>Dark-colored urine</li><li>Pale or clay-colored stools</li><li>Itchiness (pruritus) everywhere on the body</li><li>Fatigue and abdominal pain (depending on the underlying cause)</li></ul>",
            "diagnosis": "A doctor will order liver function blood tests, a complete blood count (CBC), and bilirubin tests. Imaging tests (ultrasound, CT scan, MRI) are used to check for blockages in the liver or bile ducts.",
            "treatment": "Treatment is entirely dependent on the underlying cause. If caused by a gallstone, surgery is required. If caused by a viral infection (hepatitis), antiviral medications and rest are prescribed. If caused by medicine toxicity, the medicine must be stopped.",
            "medicines": "<ul><li>Medications depend on the cause.</li><li>**Antihistamines:** May be prescribed to relieve the severe itching associated with high bilirubin.</li></ul>",
            "diet": "**To Eat:** A liver-friendly diet with lean proteins, lots of vegetables, and plenty of water to help the kidneys excrete the excess bilirubin.<br>**To Avoid:** ALCOHOL MUST BE STRICTLY AVOIDED. Avoid high-fat diets, which are hard on the gallbladder and liver.",
            "home_remedies": "<ul><li>Rest extensively to allow the liver to heal.</li><li>Avoid any unnecessary over-the-counter medications (especially Acetaminophen/Tylenol) unless approved by a doctor.</li></ul>",
            "prevention": "Protect liver health. Avoid excessive alcohol consumption, get vaccinated against Hepatitis A and B, practice safe sex, and maintain a healthy weight to prevent gallstones and fatty liver disease.",
            "recovery_time": "Depends entirely on the cause. Mild hepatitis may resolve in weeks. Jaundice caused by cirrhosis represents chronic, severe liver damage.",
            "when_to_see_doctor": "See a doctor immediately upon noticing a yellowing of your skin or eyes. Jaundice in adults is almost always a serious medical warning sign."
        },
        {
            "title": "Irritable Bowel Syndrome (IBS)",
            "category": "Digestive System Disease",
            "definition": "A common disorder that affects the large intestine. It is a chronic condition causing abdominal pain and changes in bowel habits without any physical damage or disease occurring in the digestive tract.",
            "causes": "The exact cause is unknown. It appears to involve miscommunication between the brain and the gut, causing abnormal muscle contractions in the intestine (either too fast or too slow) and hypersensitive nerves in the gut.",
            "risk_factors": "Being young (occurs more frequently in people under 50), being female, having a family history of IBS, and having a history of severe anxiety, depression, or stressful life events.",
            "symptoms": "**Common:**<br><ul><li>Cramping and abdominal pain (typically relieved wholly or partially by passing a bowel movement)</li><li>Excess gas and bloating</li><li>Diarrhea, constipation, or alternating periods of both</li><li>Mucus in the stool</li></ul>",
            "diagnosis": "There is no specific test for IBS. It is a diagnosis of exclusion. Doctors will run blood tests, stool tests, and sometimes a colonoscopy to rule out more serious diseases like Celiac disease or Inflammatory Bowel Disease (IBD) first.",
            "treatment": "There is no cure for IBS. Treatment focuses heavily on relieving symptoms so you can live as normally as possible through diet, lifestyle changes, and medication.",
            "medicines": "<ul><li>**Anti-diarrheal medications:** (Loperamide/Imodium).</li><li>**Laxatives:** For constipation-predominant IBS.</li><li>**Antispasmodics:** (Dicyclomine) to relieve severe bowel spasms.</li><li>**Antidepressants:** Low doses are often prescribed to calm the nerves in the gut.</li></ul>",
            "diet": "**To Eat:** The Low-FODMAP diet is highly effective for many. Insoluble fiber (for constipation).<br>**To Avoid:** High-FODMAP foods (certain carbs that are hard to digest: garlic, onions, wheat, dairy, certain fruits), caffeine, alcohol, and carbonated beverages.",
            "home_remedies": "<ul><li>Keep a detailed food and symptom diary to identify your specific triggers.</li><li>Eat at regular times to help regulate bowel function.</li><li>Exercise regularly to stimulate normal contractions of your intestines.</li><li>Practice stress management (Yoga, meditation).</li></ul>",
            "prevention": "IBS cannot be fully prevented, but flare-ups can be avoided by strictly adhering to your identified safe diet and managing stress levels.",
            "recovery_time": "IBS is a chronic, lifelong condition. 'Recovery' involves successfully managing the symptoms through lifestyle and dietary adjustments.",
            "when_to_see_doctor": "See a doctor if you have a persistent change in bowel habits. Seek immediate attention if you have 'red flag' symptoms like weight loss, rectal bleeding, or unexplained vomiting, as these are NOT symptoms of IBS."
        },
        {
            "title": "Acne Vulgaris",
            "category": "Skin Disease",
            "definition": "A common skin condition that occurs when your hair follicles become plugged with oil and dead skin cells. It causes whiteheads, blackheads, or pimples.",
            "causes": "Four main factors cause acne: Excess oil (sebum) production, hair follicles clogged by oil and dead skin cells, bacteria (Cutibacterium acnes), and inflammation.",
            "risk_factors": "Hormonal changes (puberty, pregnancy), taking certain medications (corticosteroids, testosterone), family history, and using oily or greasy lotions/creams.",
            "symptoms": "**Common:**<br><ul><li>Whiteheads (closed plugged pores)</li><li>Blackheads (open plugged pores)</li><li>Small red, tender bumps (papules)</li><li>Pimples (pustules), which are papules with pus at their tips</li><li>Large, solid, painful lumps under the skin (nodules/cysts)</li></ul>",
            "diagnosis": "Diagnosed by a doctor or dermatologist through a simple physical examination of your face, chest, or back.",
            "treatment": "Treatment focuses on reducing oil production, speeding up skin cell turnover, fighting bacterial infection, and reducing inflammation.",
            "medicines": "<ul><li>**Topicals:** Retinoids (Tretinoin), Benzoyl Peroxide, Salicylic Acid, Topical Antibiotics.</li><li>**Oral Medications:** Oral antibiotics for severe inflammation, combined oral contraceptives (for women), or Isotretinoin (Accutane) for severe, cystic acne.</li></ul>",
            "diet": "**To Eat:** A low-glycemic diet with whole foods, fruits, and vegetables. Foods rich in Omega-3 (fish).<br>**To Avoid:** High-glycemic-index foods (sugary foods, white bread, white rice) and excessive dairy (especially skim milk) have been associated with worsening acne in some individuals.",
            "home_remedies": "<ul><li>Wash problem areas gently with a mild cleanser twice a day.</li><li>DO NOT pick or squeeze pimples, which causes infection and permanent scarring.</li><li>Avoid touching your face with dirty hands or an unwashed phone.</li><li>Shower immediately after exercising.</li></ul>",
            "prevention": "Use noncomedogenic (won't clog pores) makeup and moisturizers. Wash your face before going to bed. Keep your hair clean and out of your face.",
            "recovery_time": "Acne treatments take time. It often takes 4 to 8 weeks of consistent daily treatment to see noticeable improvement, and skin may look worse before it gets better.",
            "when_to_see_doctor": "See a dermatologist if over-the-counter products haven't cleared up your acne, or if your acne is cystic, painful, or starting to leave permanent scars."
        },
        {
            "title": "Eczema (Atopic Dermatitis)",
            "category": "Skin Disease",
            "definition": "A condition that makes your skin red, inflamed, and intensely itchy. It is common in children but can occur at any age. It is chronic and tends to flare periodically.",
            "causes": "Related to a gene variation that affects the skin's ability to provide protection, allowing skin to be affected by environmental factors, irritants, and allergens. It is closely related to allergies and asthma.",
            "risk_factors": "A personal or family history of eczema, allergies, hay fever, or asthma.",
            "symptoms": "**Common:**<br><ul><li>Dry, intensely itchy skin (often worse at night)</li><li>Red to brownish-gray patches (especially on the hands, feet, ankles, wrists, neck, upper chest, eyelids, inside the bend of the elbows and knees)</li><li>Small, raised bumps, which may leak fluid and crust over when scratched</li><li>Thickened, cracked, scaly skin</li></ul>",
            "diagnosis": "Diagnosed primarily via a physical examination of the skin and a review of your medical history. Patch testing may be done to rule out other diseases or identify allergies.",
            "treatment": "There is no cure for atopic dermatitis. Treatments involve regular moisturizing and using prescription creams to control itching and repair the skin barrier.",
            "medicines": "<ul><li>**Topical Corticosteroids:** Creams or ointments to control inflammation and itching during flare-ups.</li><li>**Topical Calcineurin Inhibitors:** (Tacrolimus) for sensitive areas like the face.</li><li>**Antihistamines:** Oral pills to help with severe itching, especially at night.</li><li>**Biologics:** (Dupilumab) for severe, uncontrolled cases.</li></ul>",
            "diet": "**To Eat:** Anti-inflammatory foods. identifying and avoiding specific personal food triggers is more important than a general diet.<br>**To Avoid:** Certain foods (like eggs, milk, soy, and wheat) can trigger flare-ups in young children or those with specific allergies.",
            "home_remedies": "<ul><li>Moisturize your skin at least twice a day with a thick cream or ointment.</li><li>Take shorter, warm (not hot!) baths or showers.</li><li>Use gentle, non-soap cleansers. DO NOT use antibacterial or heavily scented soaps.</li><li>Wear soft, breathable cotton clothing.</li></ul>",
            "prevention": "Establish a strict daily skincare routine focused on massive moisturization immediately after bathing. Avoid known triggers (sweat, stress, certain fabrics like wool).",
            "recovery_time": "It is a chronic condition without a permanent cure. Flares can usually be cleared up within a week or two using prescription creams, followed by maintenance moisturization.",
            "when_to_see_doctor": "See a doctor if the condition affects your sleep and daily activities, if the skin looks infected (red streaks, yellow scabs, pus), or if you experience a sudden, severe flare-up."
        },
        {
            "title": "Psoriasis",
            "category": "Skin Disease",
            "definition": "A skin disease that causes a rash with itchy, scaly patches, most commonly on the knees, elbows, trunk, and scalp. It is an autoimmune condition that causes skin cells to multiply up to 10 times faster than normal.",
            "causes": "An immune system problem that causes the skin to regenerate at faster than normal rates. Genetics play a major role, and flares are triggered by environmental factors like stress, cold weather, or infections.",
            "risk_factors": "Having a family history of psoriasis, viral or bacterial infections (especially strep throat), high stress levels, obesity, and smoking.",
            "symptoms": "**Common:**<br><ul><li>Red patches of skin covered with thick, silvery scales (plaques)</li><li>Small scaling spots (commonly seen in children)</li><li>Dry, cracked skin that may bleed or itch</li><li>Itching, burning, or soreness</li><li>Thickened, pitted, or ridged nails</li><li>Swollen and stiff joints (Psoriatic arthritis)</li></ul>",
            "diagnosis": "Diagnosed by a dermatologist examining your skin, scalp, and nails. A small skin biopsy may occasionally be taken to rule out other disorders like eczema.",
            "treatment": "Treatments aim to stop skin cells from growing so quickly and to remove scales. Options range from creams and light therapy to powerful systemic medications.",
            "medicines": "<ul><li>**Topical treatments:** Corticosteroids, Vitamin D analogues (Calcipotriene), Retinoids.</li><li>**Systemic treatments:** Oral medications like Methotrexate or Cyclosporine.</li><li>**Biologics:** Highly targeted injectable immune-modulators (e.g., Humira, Stelara, Cosentyx) for moderate to severe cases.</li></ul>",
            "diet": "**To Eat:** An anti-inflammatory diet. Weight loss is highly recommended if overweight, as obesity drastically worsens psoriasis. Foods rich in Omega-3s.<br>**To Avoid:** Alcohol (can trigger outbreaks and interfere with medications), smoking, and highly processed diets.",
            "home_remedies": "<ul><li>Take daily baths with colloidal oatmeal or Epsom salts to help remove scales and calm inflamed skin.</li><li>Apply thick moisturizers immediately after bathing.</li><li>Get small amounts of natural, carefully controlled sunlight (UV light slows skin turnover, but sunburns trigger flares).</li><li>Manage stress strictly.</li></ul>",
            "prevention": "You cannot prevent psoriasis if you are genetically predisposed, but you can prevent flares by avoiding your triggers (stress, smoking, skin injuries like sunburns or scratches).",
            "recovery_time": "Psoriasis is a chronic, lifelong disease. With modern biologic treatments, many patients achieve 100% clear skin, but the disease will return if treatment stops.",
            "when_to_see_doctor": "See a dermatologist if you suspect you have psoriasis, if your psoriasis causes severe discomfort, covers a large area of your body, or if you develop joint pain and swelling."
        },
        {
            "title": "Ringworm (Tinea Corporis)",
            "category": "Skin Disease",
            "definition": "A common fungal infection of the skin. It gets its name from the characteristic ring-shaped, red, itchy rash it causes. It has absolutely nothing to do with actual worms.",
            "causes": "Caused by mold-like fungi (dermatophytes) that live on the dead tissues of your skin, hair, and nails. It is highly contagious and spreads by direct skin-to-skin contact with an infected person or animal.",
            "risk_factors": "Living in a warm climate, coming into close contact with an infected person or animal (especially puppies or kittens), sharing clothing or towels, participating in contact sports (like wrestling), and having a weak immune system.",
            "symptoms": "**Common:**<br><ul><li>A ring-shaped red, scaly area.</li><li>The rash usually has slightly raised, expanding edges with a clearer center.</li><li>Intense itching.</li><li>Overlapping rings in multiple areas.</li></ul>",
            "diagnosis": "Most often diagnosed simply by its characteristic ring-like appearance. If unclear, a doctor may take a skin scraping to examine under a microscope or send to a lab for an exact fungal culture.",
            "treatment": "Treated simply and effectively with antifungal medications. Most cases clear up with topical creams.",
            "medicines": "<ul><li>**Over-the-counter antifungals:** Clotrimazole, Miconazole, Terbinafine (Lamisil), or Tolnaftate.</li><li>**Prescription oral antifungals:** (Terbinafine pills) only used for severe, widespread cases or if it infects the scalp (Tinea capitis) or nails.</li></ul>",
            "diet": "**To Eat/Avoid:** Diet does not generally affect the contraction or treatment of a topical fungal infection like ringworm.",
            "home_remedies": "<ul><li>Wash your bedding and clothes daily while infected.</li><li>Keep the infected area clean and totally dry (fungus thrives in moisture).</li><li>Do NOT cover it with bandages; let it air out.</li></ul>",
            "prevention": "Do not share clothing, towels, hairbrushes, or sports gear. Wash your hands after playing with pets. Shower immediately after contact sports.",
            "recovery_time": "Over-the-counter creams generally cure ringworm in 2 to 4 weeks. You must continue using the cream for a week after the rash disappears to ensure the fungus is dead.",
            "when_to_see_doctor": "See a doctor if the rash doesn't begin to improve after two weeks of using an over-the-counter antifungal cream, or if you develop ringworm on your scalp (which requires oral prescription medication)."
        }
    ]
