def get_lifestyle_respiratory_diseases():
    return [
        {
            "title": "Hypertension (High Blood Pressure)",
            "category": "Lifestyle Disease",
            "definition": "A common condition in which the long-term force of the blood against your artery walls is high enough that it may eventually cause health problems, such as heart disease.",
            "causes": "Primary hypertension develops over many years with no identifiable cause. Secondary hypertension is caused by an underlying condition (like kidney disease, thyroid problems, or sleep apnea).",
            "risk_factors": "Age, family history, being overweight or obese, not being physically active, using tobacco, too much salt (sodium) in your diet, too little potassium, drinking too much alcohol, and chronic stress.",
            "symptoms": "**'The Silent Killer':** Most people have absolutely no symptoms, even if blood pressure readings reach dangerously high levels.<br>**Rare/Severe cases (Hypertensive crisis):**<br><ul><li>Severe headaches</li><li>Shortness of breath</li><li>Nosebleeds</li></ul>",
            "diagnosis": "Diagnosed with a simple, painless blood pressure measurement using an inflatable arm cuff (sphygmomanometer). Usually requires several high readings over a period of time to confirm.",
            "treatment": "Treatment involves significant lifestyle changes combined with medications. High blood pressure usually requires lifelong management.",
            "medicines": "<ul><li>**Diuretics (Water Pills):** Help your body eliminate sodium and water.</li><li>**ACE inhibitors** and **ARBs:** Help relax blood vessels.</li><li>**Calcium channel blockers:** Relax the muscles of blood vessels.</li><li>**Beta-blockers:** Reduce the workload on the heart.</li></ul>",
            "diet": "**To Eat:** The DASH (Dietary Approaches to Stop Hypertension) diet. High in fruits, vegetables, and whole grains. Rich in potassium, calcium, and magnesium.<br>**To Avoid:** SODIUM (salt) is the biggest enemy. Avoid processed foods, fast food, canned soups, and excessive alcohol.",
            "home_remedies": "<ul><li>Lose extra pounds and watch your waistline.</li><li>Exercise at least 150 minutes a week.</li><li>Quit smoking immediately.</li><li>Practice stress-reduction techniques (deep breathing, meditation).</li></ul>",
            "prevention": "Maintain a healthy weight, eat a heart-healthy diet, reduce sodium intake, limit alcohol consumption, and get regular aerobic exercise.",
            "recovery_time": "Hypertension is a chronic condition that does not 'recover' but must be managed daily to prevent heart attacks or strokes.",
            "when_to_see_doctor": "Check your blood pressure regularly. See a doctor immediately if an at-home reading is severely high (180/120 or higher) or accompanied by chest pain or vision changes."
        },
        {
            "title": "Obesity",
            "category": "Lifestyle Disease",
            "definition": "A complex disease involving an excessive amount of body fat. It is a medical problem that increases the risk of other diseases and health problems, such as heart disease, diabetes, high blood pressure, and certain cancers.",
            "causes": "Fundamentally caused by taking in more calories than you burn through daily activities and exercise. Genetics, hormonal influences, and metabolic rates also play massive roles.",
            "risk_factors": "Family inheritance, unhealthy dietary choices, liquid calories (sugary sodas), inactivity, certain medical conditions (like Prader-Willi syndrome or PCOS), and certain medications (like antidepressants or steroids).",
            "symptoms": "**Physical:**<br><ul><li>Breathlessness</li><li>Increased sweating</li><li>Snoring or sleep apnea</li><li>Inability to cope with sudden physical activity</li><li>Feeling very tired every day</li><li>Back and joint pain</li></ul>",
            "diagnosis": "Diagnosed primarily by calculating Body Mass Index (BMI). A BMI of 30 or higher is typically considered obese. Doctors also measure waist circumference and screen for related conditions (blood tests for cholesterol and blood sugar).",
            "treatment": "The goal is reaching and staying at a healthy weight. This involves dietary changes, increased physical activity, and behavioral changes. Prescription weight-loss drugs or bariatric surgery are options for severe cases.",
            "medicines": "<ul><li>**Prescription weight-loss drugs:** Liraglutide (Saxenda), Semaglutide (Wegovy), Orlistat (Xenical), Phentermine-topiramate (Qsymia). (These are strictly regulated).</li></ul>",
            "diet": "**To Eat:** Nutrient-dense, low-calorie foods. Lots of vegetables, complex carbohydrates (whole grains), and lean proteins.<br>**To Avoid:** High-calorie, high-fat, and highly processed foods. Sugary snacks, fast food, and large portion sizes.",
            "home_remedies": "<ul><li>Join a support group or counseling to address emotional eating.</li><li>Keep a strict food and activity journal.</li><li>Get plenty of sleep (sleep deprivation alters hunger hormones).</li></ul>",
            "prevention": "Eat three balanced meals a day, focus on low-calorie, nutrient-dense foods, avoid saturated fat, limit sweets and alcohol, and exercise regularly (150-300 minutes a week).",
            "recovery_time": "Obesity requires lifelong commitment to diet and exercise habits. Weight loss is a gradual, ongoing process, not a quick fix.",
            "when_to_see_doctor": "See a doctor if you are concerned about your weight or if obesity is causing joint pain, sleep problems, or emotional distress. A doctor can help initiate a safe weight-loss plan."
        },
        {
            "title": "Coronary Artery Disease (CAD)",
            "category": "Lifestyle Disease",
            "definition": "The most common type of heart disease. It occurs when the arteries that supply blood to the heart muscle become hardened and narrowed, limiting blood flow.",
            "causes": "Mainly caused by atherosclerosis—a buildup of cholesterol-containing deposits (plaque) and inflammation inside the coronary arteries.",
            "risk_factors": "High blood pressure, high blood cholesterol, smoking, diabetes, obesity, physical inactivity, unhealthy diet, age, and a family history of heart disease.",
            "symptoms": "**Early:** Often asymptomatic until severe blockages exist.<br>**Classic:**<br><ul><li>Angina (chest pain, pressure, or tightness)</li><li>Shortness of breath</li><li>Heart attack (a completely blocked artery causing crushing chest pain radiating to the arm/jaw)</li></ul>",
            "diagnosis": "Diagnosed using an Electrocardiogram (ECG/EKG), Echocardiogram, Exercise stress test, Cardiac CT scan, or Coronary Angiogram (cardiac catheterization).",
            "treatment": "Treatment involves a combination of aggressive lifestyle changes, daily medications, and sometimes medical procedures like angioplasty (stents) or coronary artery bypass surgery.",
            "medicines": "<ul><li>**Statins/Cholesterol drugs:** To lower plaque buildup.</li><li>**Aspirin:** To prevent blood clots.</li><li>**Beta-blockers:** To slow heart rate and lower blood pressure.</li><li>**Nitroglycerin:** To temporarily widen arteries and relieve chest pain (angina).</li></ul>",
            "diet": "**To Eat:** A strictly heart-healthy Mediterranean diet. High in vegetables, fruits, whole grains, nuts, and fish high in omega-3 fatty acids.<br>**To Avoid:** Saturated fats, trans fats, excessive salt, and refined sugars.",
            "home_remedies": "<ul><li>Stop smoking completely.</li><li>Manage stress (chronic high stress damages arteries).</li><li>Engage in moderate, doctor-approved exercise daily (like brisk walking).</li></ul>",
            "prevention": "Control blood pressure, cholesterol, and diabetes. Don't smoke. Eat healthy, exercise, and maintain a healthy weight.",
            "recovery_time": "CAD is a chronic, progressive disease. Symptoms can be managed and heart attacks prevented with strict medical and lifestyle adherence.",
            "when_to_see_doctor": "CALL EMERGENCY SERVICES IMMEDIATELY if you experience crushing chest pain, pressure in the chest, shortness of breath, or pain radiating to your left arm or jaw (signs of a heart attack)."
        },
        {
            "title": "Stroke",
            "category": "Lifestyle Disease",
            "definition": "A medical emergency that occurs when the blood supply to part of the brain is interrupted or reduced, preventing brain tissue from getting oxygen and nutrients. Brain cells begin to die in minutes.",
            "causes": "Two main causes: a blocked artery (Ischemic stroke, the most common type) or leaking/bursting of a blood vessel (Hemorrhagic stroke). A temporary disruption is a TIA (mini-stroke).",
            "risk_factors": "High blood pressure (the #1 risk factor), smoking, diabetes, high cholesterol, obesity, obstructive sleep apnea, cardiovascular disease, and heavy drinking.",
            "symptoms": "**Think 'F.A.S.T.':**<br><ul><li>**F**ace drooping (one side of the face is numb or droops).</li><li>**A**rm weakness (one arm is numb or drifts downward).</li><li>**S**peech difficulty (slurred speech or unable to speak).</li><li>**T**ime to call emergency services.</li></ul>",
            "diagnosis": "Time is critical. Doctors will immediately perform a CT or MRI scan of the brain to determine if it is ischemic (blocked) or hemorrhagic (bleeding). Blood tests and echocardiograms are also used.",
            "treatment": "**Ischemic:** Restoring blood flow quickly using IV clot-busting medication (tPA) or mechanical clot removal.<br>**Hemorrhagic:** Controlling bleeding and reducing pressure in your brain via blood pressure meds or surgery.",
            "medicines": "<ul><li>**Thrombolytics (tPA):** Clot busters (must be given within hours).</li><li>**Antiplatelets/Anticoagulants (Aspirin, Warfarin):** To prevent future clots.</li><li>**Blood pressure drugs:** To prevent recurrent strokes.</li></ul>",
            "diet": "**To Eat:** A heart-healthy diet to manage blood pressure and cholesterol. High in fruits, vegetables, completely lean proteins.<br>**To Avoid:** Excess sodium (salt), saturated fats, and alcohol.",
            "home_remedies": "<ul><li>There are NO home remedies for an active stroke; it is a profound medical emergency.</li><li>For recovery, rigorous physical, occupational, and speech therapy is required.</li></ul>",
            "prevention": "Aggressively manage high blood pressure. Quit smoking. Manage diabetes and cholesterol. Maintain a healthy weight and exercise.",
            "recovery_time": "Varies drastically. Some recover quickly, while others suffer permanent disability and require years of intensive physical and speech therapy.",
            "when_to_see_doctor": "CALL 911 OR EMERGENCY HEALTH SERVICES IMMEDIATELY at the very first sign of a stroke. Do not wait to see if symptoms stop."
        },
        {
            "title": "Asthma",
            "category": "Respiratory Disease",
            "definition": "A condition in which your airways narrow and swell and may produce extra mucus. This can make breathing difficult and trigger coughing, a whistling sound (wheezing) when you breathe out, and shortness of breath.",
            "causes": "The exact cause is unknown, but it's likely due to a combination of environmental and genetic (inherited) factors. Exposure to various irritants and substances that trigger allergies (allergens) can trigger signs and symptoms of asthma.",
            "risk_factors": "Having a blood relative with asthma, having an allergic condition (atopic dermatitis, hay fever), being overweight, smoking, exposure to secondhand smoke or exhaust fumes.",
            "symptoms": "**Common:**<br><ul><li>Shortness of breath</li><li>Chest tightness or pain</li><li>Wheezing when exhaling (especially common in children)</li><li>Trouble sleeping caused by shortness of breath, coughing or wheezing</li><li>Coughing or wheezing attacks worsened by a respiratory virus (cold or flu)</li></ul>",
            "diagnosis": "Diagnosed via a physical exam and lung (pulmonary) function tests, primarily spirometry, to measure how much air you can exhale and how fast you can exhale. Doctors may also use Methacholine challenge tests or allergy testing.",
            "treatment": "Prevention and long-term control are key in stopping asthma attacks before they start. Treatment usually involves learning to recognize triggers, taking steps to avoid them, and tracking your breathing to make sure your medications are keeping symptoms under control.",
            "medicines": "<ul><li>**Long-term control:** Inhaled corticosteroids (Fluticasone, Budesonide), Leukotriene modifiers (Singulair).</li><li>**Quick-relief (rescue):** Short-acting beta agonists (Albuterol) via an inhaler for rapid symptom relief during an attack.</li></ul>",
            "diet": "**To Eat:** An anti-inflammatory diet high in Omega-3 fatty acids (flaxseeds, salmon) and Vitamin D (milk, eggs) may help reduce airway inflammation.<br>**To Avoid:** Foods that trigger an allergic reaction (if you have food allergies), sulfites found in wine and dried fruits.",
            "home_remedies": "<ul><li>Identify and eliminate asthma triggers (dust mites, pet dander, mold).</li><li>Use an air conditioner or air purifier with a HEPA filter.</li><li>Maintain optimal indoor humidity (between 30% and 50%).</li><li>Clean regularly to reduce dust.</li></ul>",
            "prevention": "Asthma cannot be prevented, but attacks can be prevented by following your asthma action plan, getting vaccinated for influenza and pneumonia, identifying triggers, and taking your medication as prescribed.",
            "recovery_time": "Asthma is a chronic condition. While an asthma attack can resolve in minutes with an inhaler, the underlying condition requires lifelong management.",
            "when_to_see_doctor": "Seek emergency care if you have severe shortness of breath/wheezing, or no improvement even after using your quick-relief inhaler."
        },
        {
            "title": "Bronchitis",
            "category": "Respiratory Disease",
            "definition": "An inflammation of the lining of your bronchial tubes, which carry air to and from your lungs. People who have bronchitis often cough up thickened mucus, which can be discolored.",
            "causes": "Acute bronchitis is usually caused by viruses, typically the same viruses that cause colds and flu (influenza). Chronic bronchitis is most often caused by cigarette smoking.",
            "risk_factors": "Cigarette smoke (including secondhand smoke), low resistance (especially in the elderly, infants, or those with underlying diseases), exposure to irritants on the job (grain dust, textiles, chemical fumes), and gastric reflux.",
            "symptoms": "**Common to both acute and chronic:**<br><ul><li>Cough (the hallmark symptom)</li><li>Production of mucus (sputum), which can be clear, white, yellowish-gray, or green in color</li><li>Fatigue</li><li>Shortness of breath</li><li>Slight fever and chills</li><li>Chest discomfort</li></ul>",
            "diagnosis": "For acute bronchitis, a doctor will usually diagnose it using a stethoscope during a physical exam. For suspected chronic bronchitis or pneumonia, chest X-rays, sputum tests, and pulmonary function tests are used.",
            "treatment": "Most cases of acute bronchitis get better without medical treatment within a couple of weeks. Antibiotics are generally not prescribed, as most cases are viral.",
            "medicines": "<ul><li>**Cough suppressants:** Only for use if coughing keeps you awake; it's best to cough up mucus.</li><li>**Inhalers/Nebulizers:** Short-acting bronchodilators to open airways if you are wheezing.</li><li>**OTC Meds:** Acetaminophen or Ibuprofen for fever/aches.</li></ul>",
            "diet": "**To Eat:** Warm liquids such as chicken soup, hot water with lemon and honey, and herbal teas. Stay extremely well hydrated to thin out mucus.<br>**To Avoid:** Dairy products (can thicken mucus), caffeine, and alcohol (dehydrating).",
            "home_remedies": "<ul><li>Get large amounts of rest.</li><li>Drink plenty of fluids.</li><li>Breathe in warm, moist air (use a humidifier or sit in a steamy bathroom).</li><li>Use lozenges to soothe your throat.</li></ul>",
            "prevention": "Avoid cigarette smoke. Get vaccinated against the flu and pneumonia. Wash your hands frequently to reduce exposure to viruses. Wear a mask if you must be exposed to dust or fumes.",
            "recovery_time": "Acute bronchitis improves in a few days, but the cough can last for 2 to 3 weeks. Chronic bronchitis requires long-term medical management.",
            "when_to_see_doctor": "See your doctor if your cough lasts more than three weeks, prevents you from sleeping, is accompanied by a fever higher than 100.4°F (38°C), or produces blood or rust-colored mucus."
        },
        {
            "title": "Pneumonia",
            "category": "Respiratory Disease",
            "definition": "An infection that inflames the air sacs in one or both lungs. The air sacs may fill with fluid or pus (purulent material), causing cough with phlegm or pus, fever, chills, and difficulty breathing.",
            "causes": "Caused by a variety of organisms, including bacteria, viruses, and fungi. The most common bacterial cause in the U.S. is *Streptococcus pneumoniae*.",
            "risk_factors": "Being older than 65, being younger than 2, having a weakened immune system (HIV/AIDS, organ transplant, chemotherapy), smoking, and having chronic diseases (asthma, COPD, heart disease).",
            "symptoms": "**Common:**<br><ul><li>Cough, which may produce greenish, yellow, or even bloody mucus</li><li>Fever, sweating, and shaking chills</li><li>Shortness of breath, even when resting</li><li>Rapid, shallow breathing</li><li>Sharp or stabbing chest pain that gets worse when you breathe deeply or cough</li><li>Fatigue and muscle aches</li></ul>",
            "diagnosis": "Diagnosed primarily using a chest X-ray to determine the extent and location of the infection. Doctors will also use a stethoscope to listen for crackling sounds in the lungs, perform blood tests, and use a pulse oximeter.",
            "treatment": "Treatment depends on the type of pneumonia. Bacterial pneumonia is treated with antibiotics. Viral pneumonia requires rest and fluids (antivirals may be used). Severe cases require hospitalization for IV antibiotics and oxygen therapy.",
            "medicines": "<ul><li>**Antibiotics:** (e.g., Azithromycin, Levofloxacin, Amoxicillin) to target bacterial pneumonia.</li><li>**Cough medicine:** To calm the cough so you can rest.</li><li>**Fever/Pain relievers:** Ibuprofen or Acetaminophen.</li></ul>",
            "diet": "**To Eat:** A nutritious diet to support your immune system. High Vitamin C and Zinc. Clear broths, warm water.<br>**To Avoid:** High sugar, heavy/greasy meals that take energy to digest.",
            "home_remedies": "<ul><li>Get plenty of rest (people often try to return to their routine too soon).</li><li>Drink plenty of fluids to help loosen mucus in your lungs.</li><li>Take all your medications exactly as prescribed.</li></ul>",
            "prevention": "Get vaccinated (Prevnar 13, Pneumovax 23, and the annual flu shot). Practice good hygiene, don't smoke (smoking damages the lungs' natural defenses), and keep your immune system strong.",
            "recovery_time": "With antibiotics, you often feel better in 2-3 days, but tiredness and a lingering cough can last a month or more. Severe cases can take much longer.",
            "when_to_see_doctor": "Seek medical attention IMMEDIATELY if you have difficulty breathing, chest pain, a persistent fever of 102°F (39°C) or higher, or a persistent cough, especially if you are coughing up pus."
        },
        {
            "title": "Chronic Obstructive Pulmonary Disease (COPD)",
            "category": "Respiratory Disease",
            "definition": "A chronic inflammatory lung disease that causes obstructed airflow from the lungs. Emphysema and chronic bronchitis are the two most common conditions that contribute to COPD.",
            "causes": "In the vast majority of cases in developed countries, the cause of COPD is long-term tobacco smoking. In developing countries, COPD often occurs in people exposed to fumes from burning fuel for cooking and heating in poorly ventilated homes.",
            "risk_factors": "Exposure to tobacco smoke (the most significant risk factor), people with asthma who smoke, occupational exposure to dusts and chemicals, exposure to fumes from burning fuel, genetics (Alpha-1-antitrypsin deficiency).",
            "symptoms": "**Early:**<br><ul><li>A persistent cough or a cough that produces a lot of mucus (often called 'smoker's cough')</li><li>Shortness of breath, especially during physical activities</li><li>Wheezing</li><li>Chest tightness</li></ul>**Later:**<br><ul><li>Frequent respiratory infections</li><li>Lack of energy</li><li>Unintended weight loss (in later stages)</li><li>Swelling in ankles, feet, or legs</li></ul>",
            "diagnosis": "Diagnosed mainly through spirometry (a lung function test) which measures how much air your lungs can hold and how fast you can blow it out. Chest X-rays, CT scans, and arterial blood gas analysis are also used.",
            "treatment": "COPD cannot be cured, but treatment can ease symptoms, prevent complications, and slow disease progression. Quitting smoking is the absolutely essential first step.",
            "medicines": "<ul><li>**Bronchodilators (Inhalers):** Relax the muscles around airways (e.g., Albuterol, Ipratropium).</li><li>**Inhaled corticosteroids:** Reduce airway inflammation.</li><li>**Oral steroids:** For severe exacerbations.</li><li>**Antibiotics:** Prescribed during symptom flare-ups caused by bacterial infections.</li></ul>",
            "diet": "**To Eat:** Eating small, frequent meals. High-fiber foods, lean proteins. Some people need extra calories because breathing with COPD burns a lot of energy.<br>**To Avoid:** Gassy foods (beans, cabbage) which can bloat the stomach and push against the diaphragm, making breathing harder. Too much salt.",
            "home_remedies": "<ul><li>STOP SMOKING entirely.</li><li>Clear airways daily using controlled coughing or mucus clearance devices.</li><li>Exercise regularly to improve your overall strength and endurance, though lung function won't improve.</li><li>Use supplemental oxygen if prescribed.</li></ul>",
            "prevention": "Never start smoking. If you do smoke, quit immediately. Avoid occupational exposure to chemical fumes and dust.",
            "recovery_time": "COPD is an ongoing, progressive disease. You do not recover from it, but you can slow its progression significantly by quitting smoking and following treatment.",
            "when_to_see_doctor": "See a doctor if you have signs of COPD. Seek emergency care if you have severe shortness of breath, a blue hue to your lips or fingernails, or a rapid heartbeat."
        }
    ]
